// Copyright 2024 Google, LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.com/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package commands provides the concrete implementations of the Chain of
// Responsibility (COR) pattern's Command interface. This file defines the
// command responsible for assembling the final, complete media object.
//
// Logic Flow:
// This command acts as a final assembly step in the media processing workflow.
// It takes the high-level summary information (title, cast, etc.) and the
// detailed, per-scene information generated by previous commands and combines
// them into a single, cohesive `model.Media` struct. This struct is then
// ready for persistence.
//
//  1. Receives two inputs from the context:
//     a) A `model.MediaSummary` struct.
//     b) A slice of strings, where each string is a JSON representation of a `model.Scene`.
//  2. Joins the scene JSON strings into a single valid JSON array string.
//  3. Unmarshals (parses) this JSON array into a slice of `model.Scene` structs.
//  4. Sorts the scenes chronologically based on their start time. This is
//     important because scene extraction may have happened in parallel and out of order.
//  5. Re-sequences the scenes by assigning a new sequence number after sorting.
//  6. Creates a new `model.Media` object (which also generates a UUID for the ID).
//  7. Populates the `model.Media` object with all the data from the summary
//     and the newly sorted and sequenced scenes.
//  8. Places the final, assembled `model.Media` object back into the context
//     for the next command (likely persistence) to use.
package commands

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jaycherian/gcp-go-media-search/internal/core/cor"
	"github.com/jaycherian/gcp-go-media-search/internal/core/model"
)

// DefaultMovieTimeFormat defines the expected time format (HH:MM:SS) for scene start/end times.
const (
	DefaultMovieTimeFormat = "15:04:05"
)

// MediaAssembly is a command that combines a media summary and a collection of scenes
// into a single, complete Media object.
type MediaAssembly struct {
	cor.BaseCommand
	summaryParam     string // The context key for the input MediaSummary struct.
	sceneParam       string // The context key for the input slice of scene JSON strings.
	mediaObjectParam string // The context key where the final assembled Media object will be stored.
}

// NewMediaAssembly is the constructor for the MediaAssembly command.
//
// Inputs:
//   - name: A string name for this command instance.
//   - summaryParam: The name of the context parameter holding the `model.MediaSummary`.
//   - sceneParam: The name of the context parameter holding the slice of scene JSON strings.
//   - mediaObjectParam: The name of the context parameter to store the output `model.Media` object.
//
// Outputs:
//   - *MediaAssembly: A pointer to the newly instantiated command.
func NewMediaAssembly(name string, summaryParam string, sceneParam string, mediaObjectParam string) *MediaAssembly {
	return &MediaAssembly{
		BaseCommand:      *cor.NewBaseCommand(name),
		summaryParam:     summaryParam,
		sceneParam:       sceneParam,
		mediaObjectParam: mediaObjectParam}
}

// IsExecutable overrides the default behavior to ensure that both the summary
// and scene parameters are present in the context before execution.
//
// Inputs:
//   - context: The shared `cor.Context` for this workflow execution.
//
// Outputs:
//   - bool: True if the required parameters exist, otherwise false.
func (m *MediaAssembly) IsExecutable(context cor.Context) bool {
	return context != nil &&
		context.Get(m.summaryParam) != nil &&
		context.Get(m.sceneParam) != nil
}

// Execute performs the assembly logic.
//
// Inputs:
//   - context: The shared `cor.Context` for this workflow execution.
func (m *MediaAssembly) Execute(context cor.Context) {
	// Retrieve the inputs from the context.
	summary := context.Get(m.summaryParam).(*model.MediaSummary)
	jsonScenes := context.Get(m.sceneParam).([]string)

	// The scene data comes in as a slice of JSON strings: `["{...}", "{...}"]`.
	// We join them with a comma and wrap them in brackets to create a valid JSON array string: `"[ {...} , {...} ]"`.
	sceneValues := fmt.Sprintf("[ %s ]", strings.Join(jsonScenes, ","))

	// Unmarshal the JSON array string into a slice of Scene structs.
	scenes := make([]*model.Scene, 0)
	sceneErr := json.Unmarshal([]byte(sceneValues), &scenes)
	if sceneErr != nil {
		m.GetErrorCounter().Add(context.GetContext(), 1)
		context.AddError(m.GetName(), sceneErr)
		return
	}

	// Sort the scenes chronologically. This is crucial because scene extraction
	// may have happened in parallel, so the results are not guaranteed to be in order.
	sort.Slice(scenes, func(i, j int) bool {
		// Parse the start time strings into time objects for comparison.
		t, _ := time.Parse(DefaultMovieTimeFormat, scenes[i].Start)
		tt, _ := time.Parse(DefaultMovieTimeFormat, scenes[j].Start)
		return t.Before(tt)
	})

	// After sorting, re-apply the sequence numbers to ensure they are correct.
	for i, scene := range scenes {
		scene.SequenceNumber = i + 1 // Use 1-based indexing for sequences.
	}

	// Create a new Media object. The constructor handles generating a unique ID.
	media := model.NewMedia(summary.Title)

	// Populate the Media object with data from the summary and the processed scenes.
	media.Title = summary.Title
	media.Category = summary.Category
	media.Summary = summary.Summary
	media.MediaUrl = summary.MediaUrl
	media.LengthInSeconds = summary.LengthInSeconds
	media.Director = summary.Director
	media.ReleaseYear = summary.ReleaseYear
	media.Genre = summary.Genre
	media.Rating = summary.Rating
	media.Cast = append(media.Cast, summary.Cast...)
	media.Scenes = append(media.Scenes, scenes...)

	m.GetSuccessCounter().Add(context.GetContext(), 1)

	// Place the fully assembled Media object into the specified output parameter in the context.
	context.Add(m.mediaObjectParam, media)
	// Also place it in the default output parameter for chain compatibility.
	context.Add(cor.CtxOut, media)
}
